POST http://127.0.0.1:8000/venue/

{
    "name":"Central World Arena",
    "capacity":7000
}

POST http://127.0.0.1:8000/zone/

{
    "zone_name":"C",
    "venue_id":1
}

POST http://127.0.0.1:8000/seat/

{
    "seat_position":"A5",
    "zone_id":1
}

POST http://127.0.0.1:8000/payment/paymentMethod

{
    "method":"Credit Card"
}

POST http://127.0.0.1:8000/event/

{
    "eventname":"Music Gala",
    "eventdate":"2025-10-05",
    "available_tickets":3500,
    "venue_id":1,
    "pic":"pic2.png",
    "organizer_id":2
}

POST http://127.0.0.1:8000/utility/organizer

{
    "name":"Music Events",
    "email":"music@eventsmail.com"
}

POST http://127.0.0.1:8000/ezp/

{
    "event_id":3,
    "zone_id":6,
    "price":5000
}